language: python

python:
- 3.3

env:
- DJANGO_SETTINGS_MODULE="AtYourService.travis_settings"
install:
- pip install -r requirements.txt --use-mirrors
- pip install coverage python_coveralls --use-mirrors

before_script:
- psql -c 'create database AtYourSerivce;' -U postgres
- python manage.py syncdb --noinput
- python manage.py migrate --noinput

script: coverage run manage.py test

after_success:
- coveralls
